#pragma once

#define OSW_PLATFORM_ENVIRONMENT 1
#define OSW_PLATFORM_ENVIRONMENT_TEMPERATURE 1
//#define OSW_PLATFORM_ENVIRONMENT_PRESSURE 0
//#define OSW_PLATFORM_ENVIRONMENT_HUMIDITY 0
//#define OSW_PLATFORM_ENVIRONMENT_MAGNETOMETER 0
#define OSW_PLATFORM_ENVIRONMENT_ACCELEROMETER 1

//#define OSW_PLATFORM_HARDWARE_DS3231MZ 0
//#define OSW_PLATFORM_HARDWARE_BMA400 0
#define OSW_PLATFORM_HARDWARE_BMI270 1
//#define OSW_PLATFORM_HARDWARE_BMP581 0
//#define OSW_PLATFORM_HARDWARE_QMC5883L 0
//#define OSW_PLATFORM_HARDWARE_BME280 0
//#define OSW_PLATFORM_HARDWARE_VIRTUAL 0
#define OSW_PLATFORM_HARDWARE_ESP32 1
#define OSW_PLATFORM_HARDWARE_ESP32_USE_JTAG_SERIAL 1
#define OSW_PLATFORM_HARDWARE_DISPLAY_CS 40
#define OSW_PLATFORM_HARDWARE_DISPLAY_DC 38
// well, the display reset pin is located at MAX7321ATE (U7), pin 5 (P3)
#define OSW_PLATFORM_HARDWARE_DISPLAY_RST -1
#define OSW_PLATFORM_HARDWARE_DISPLAY_SCK 41
#define OSW_PLATFORM_HARDWARE_DISPLAY_MOSI 42
#define OSW_PLATFORM_HARDWARE_DISPLAY_LED 46
#define OSW_PLATFORM_HARDWARE_DISPLAY_SPI_NUM 0
#define OSW_PLATFORM_HARDWARE_DISPLAY_ROTATION 2
//#define OSW_PLATFORM_HARDWARE_VIBRATE 0
#define OSW_PLATFORM_BLOCK_SLEEP 1 // used during the integration of new platforms to prevent the device from going to sleep
#define OSW_PLATFORM_IS_FLOW3R_BADGE 1
#define OSW_PLATFORM_DEFAULT_CPUFREQ 240

#define OSW_DEVICE_ESP32_WIFI_LOWPWR 0
//#define OSW_DEVICE_DS3231MZ_RTCINT 32
//#define OSW_DEVICE_BMA400_INT1 34
//#define OSW_DEVICE_BMA400_INT2 35
#define OSW_DEVICE_I2C_SCL 1
#define OSW_DEVICE_I2C_SDA 2
//#define OSW_DEVICE_TPS2115A_STATPWR 0
#define OSW_DEVICE_ESP32_BATLVL 9
#define OSW_DEVICE_ESP32_USE_INTTEMP 0
