#pragma once

#define OSW_PLATFORM_ENVIRONMENT 1
#define OSW_PLATFORM_ENVIRONMENT_TEMPERATURE 1
//#define OSW_PLATFORM_ENVIRONMENT_PRESSURE 0
//#define OSW_PLATFORM_ENVIRONMENT_HUMIDITY 0
//#define OSW_PLATFORM_ENVIRONMENT_MAGNETOMETER 0
#define OSW_PLATFORM_ENVIRONMENT_ACCELEROMETER 1

#define OSW_PLATFORM_HARDWARE_DS3231MZ 1
#define OSW_PLATFORM_HARDWARE_BMA400 1
//#define OSW_PLATFORM_HARDWARE_BME280 0
//#define OSW_PLATFORM_HARDWARE_QMC5883L 0