#pragma once

//#define OSW_PLATFORM_ENVIRONMENT 0
//#define OSW_PLATFORM_ENVIRONMENT_TEMPERATURE 0
//#define OSW_PLATFORM_ENVIRONMENT_PRESSURE 0
//#define OSW_PLATFORM_ENVIRONMENT_HUMIDITY 0
//#define OSW_PLATFORM_ENVIRONMENT_MAGNETOMETER 0
//#define OSW_PLATFORM_ENVIRONMENT_ACCELEROMETER 0

//#define OSW_PLATFORM_HARDWARE_DS3231MZ 0
//#define OSW_PLATFORM_HARDWARE_BMA400 0
//#define OSW_PLATFORM_HARDWARE_BMI270 0
//#define OSW_PLATFORM_HARDWARE_BMP581 0
//#define OSW_PLATFORM_HARDWARE_BME280 0
//#define OSW_PLATFORM_HARDWARE_QMC5883L 0
//#define OSW_PLATFORM_HARDWARE_VIRTUAL 0
//#define OSW_PLATFORM_HARDWARE_ESP32 0
//#define OSW_PLATFORM_HARDWARE_ESP32_USE_JTAG_SERIAL 0
#define OSW_PLATFORM_HARDWARE_DISPLAY_CS 0
#define OSW_PLATFORM_HARDWARE_DISPLAY_DC 0
//#define OSW_PLATFORM_HARDWARE_DISPLAY_RST 0
#define OSW_PLATFORM_HARDWARE_DISPLAY_SCK 0
#define OSW_PLATFORM_HARDWARE_DISPLAY_MOSI 0
//#define OSW_PLATFORM_HARDWARE_DISPLAY_LED 0
#define OSW_PLATFORM_HARDWARE_DISPLAY_SPI_NUM 0
//#define OSW_PLATFORM_HARDWARE_DISPLAY_ROTATION 0
//#define OSW_PLATFORM_HARDWARE_VIBRATE 0
//#define OSW_PLATFORM_BLOCK_SLEEP 0 // used during the integration of new platforms to prevent the device from going to sleep
//#define OSW_PLATFORM_IS_FLOW3R_BADGE 0
//#define OSW_PLATFORM_DEFAULT_CPUFREQ 0

//#define OSW_DEVICE_ESP32_WIFI_LOWPWR 0
//#define OSW_DEVICE_DS3231MZ_RTCINT 0
//#define OSW_DEVICE_BMA400_INT1 0
//#define OSW_DEVICE_BMA400_INT2 0
//#define OSW_DEVICE_I2C_SCL 0
//#define OSW_DEVICE_I2C_SDA 0
//#define OSW_DEVICE_TPS2115A_STATPWR 0
//#define OSW_DEVICE_ESP32_BATLVL 0
//#define OSW_DEVICE_ESP32_USE_INTTEMP 0
