name: Build OSW-OS (Ubuntu, additional features)

on:
  push:
    paths_ignore: '["*.md", "**/scripts/screen_capture/**"]'
  pull_request:
    branches: [ master, develop ]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.2.0
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  Find-feature:
    runs-on: ubuntu-latest
    needs: check_skip
    if: ${{ needs.check_skip.outputs.should_skip != 'true' }}
    steps:         
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - id: get-flag
        run: |
          echo "feature=$(./.github/setMatrix.sh --get-flag)" >> $GITHUB_OUTPUT
      - id: default_mod
        run: |
          echo "default_model=$(./.github/setMatrix.sh --default-mod)" >> $GITHUB_OUTPUT
      - id: default_lang
        run: |
          echo "default_language=$(./.github/setMatrix.sh --default-lang)" >> $GITHUB_OUTPUT
    outputs:
      feature: ${{ steps.get-flag.outputs.feature }}
      default_model: ${{ steps.default_mod.outputs.default_model }}
      default_language: ${{ steps.default_lang.outputs.default_language }}
  build-OSW:
    needs: Find-feature
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: ${{ fromJson(needs.Find-feature.outputs.feature) }}
        model: ${{ fromJson(needs.Find-feature.outputs.default_model) }}
        language: ${{ fromJson(needs.Find-feature.outputs.default_language) }}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: platformio-${{ runner.os }}
    - name: Install swig
      run: sudo apt-get update && sudo apt-get -y install swig
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: python -m pip install --upgrade pip && pip install --upgrade platformio
    - name: Rename config
      run: mv include/config.h.example include/config.h
    - name: Compile language ${{ matrix.language }} model ${{ matrix.model }} feature ${{ matrix.feature }}
      run: python3 .github/buildEverything.py -l ${{ matrix.language }} -m ${{ matrix.model }} -f ${{ matrix.feature }} -b debug
