name: OSW-FEATURE-test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master, develop ]

jobs:
  Find-feature:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip CI-feature') }}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - id: get-flag
        run: |
          echo "::set-output name=feature::$(./.github/setMatrix.sh --get-flag)"
      - id: default_mod
        run: |
          echo "::set-output name=default_model::$(./.github/setMatrix.sh --default-mod)"
      - id: default_lang
        run: |
          echo "::set-output name=default_language::$(./.github/setMatrix.sh --default-lang)"
    outputs:
      feature: ${{ steps.get-flag.outputs.feature }}
      default_model: ${{ steps.default_mod.outputs.default_model }}
      default_language: ${{ steps.default_lang.outputs.default_language }}
  build-OSW:
    needs: Find-feature
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip CI-feature') }}
    strategy:
      fail-fast: false
      matrix:
        feature: ${{ fromJson(needs.Find-feature.outputs.feature) }}
        model: ${{ fromJson(needs.Find-feature.outputs.default_model) }}
        language: ${{ fromJson(needs.Find-feature.outputs.default_language) }}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: cache-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install swig
      run: sudo apt-get update && sudo apt-get -y install swig
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: python -m pip install --upgrade pip && pip install --upgrade platformio
    - name: Rename config
      run: mv include/config.h.example include/config.h
    - name: Compile language ${{ matrix.language }} model ${{ matrix.model }} feature ${{ matrix.feature }}
      run: python3 .github/buildEverything.py -l ${{ matrix.language }} -m ${{ matrix.model }} -f ${{ matrix.feature }}